# TOML document for thumberd config

[font]
	name = ["IPAGothic"]

[http]
	avoid_chunk = false
	user_agent = "yoya-thumber"

[domain]
        [domain."www.example.com"]
                MaxHeaderListSize = 32768
                DisableCompression = true
                AllowHTTP = false

        [domain."www.example.org"]
                MaxHeaderListSize = 32768

[image]
	background_color = "#ffffff00"
	compression_quality = 90
	gravity = 2
	crop_mode = 0
